### ISSUE TITLE
Test failures with Python 3.12

### ISSUE THREAD

**Issue by mgorny** [Iotic-Labs/py-ubjson#18]
When running the test suite with Python 3.12.0, I'm getting two test failures:

```pytb
======================================================================
FAIL: test_recursion (test.test.TestEncodeDecodeFpExt.test_recursion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/py-ubjson/test/test.py", line 476, in test_recursion
    with self.assert_raises_regex(RuntimeError, 'recursion'):
AssertionError: RuntimeError not raised

======================================================================
FAIL: test_recursion (test.test.TestEncodeDecodePlainExt.test_recursion)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/py-ubjson/test/test.py", line 476, in test_recursion
    with self.assert_raises_regex(RuntimeError, 'recursion'):
AssertionError: RuntimeError not raised
```

**Comment by vtermanis** [comment]
It's probably a change in the default recursion limit with the latest version of Python - I'll have a look later.
