### ISSUE TITLE
0.11.0 fails floating type test on i686-linux-gnu

### ISSUE THREAD

**Issue by doko42** [Iotic-Labs/py-ubjson#5]
0.11 passes it's tests on most architectures, except in i686-linux-gnu:

======================================================================
FAIL: test_float (test.TestEncodeDecodeFp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_ubjson/build/test/test.py", line 209, in test_float
    no_float32=False)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_ubjson/build/test/test.py", line 87, in check_enc_dec
    self.type_check(encoded[0], expected_type)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_ubjson/build/test/test.py", line 59, in type_check
    self.assertEqual(actual, expected)
AssertionError: 'D' != 'd'

======================================================================
FAIL: test_float (test.TestEncodeDecodePlain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_ubjson/build/test/test.py", line 209, in test_float
    no_float32=False)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_ubjson/build/test/test.py", line 87, in check_enc_dec
    self.type_check(encoded[0], expected_type)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython2_2.7_ubjson/build/test/test.py", line 59, in type_check
    self.assertEqual(actual, expected)
AssertionError: 'D' != 'd'

----------------------------------------------------------------------
Ran 53 tests in 3.112s

FAILED (failures=2)

complete build logs at
https://launchpad.net/ubuntu/+source/py-ubjson/0.11.0-0ubuntu1

**Comment by vtermanis** [comment]
Thank you for the report @doko42  . I'm currently busy with work but shall try to have a look at this this weekend (28/07).

**Comment by vtermanis** [comment]
I think I've fixed this in https://github.com/Iotic-Labs/py-ubjson/commit/afead05ad0eab2b542dc0e606fcd91b6b4b3e573 (and have reproduced/tested on both 18.04 32-bit and 16.04 64-bit with Python 2.7 & 3.6.
@doko42 Are you able to test this on your end before I make a release? (If not, I'll make a minor release - let me know.)

**Comment by doko42** [comment]
yes, relaxing the tests helps:
https://launchpad.net/ubuntu/+source/py-ubjson/0.11.0-0ubuntu2

**Comment by vtermanis** [comment]
Thank you, I've made a new release (already on PyPI - will add anaconda version in a short while):
https://github.com/Iotic-Labs/py-ubjson/releases/tag/v0.12.0
